version: '{build}'
skip_tags: true
# NOTE: AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
clone_depth: 10
platform: x64
environment:
  APM_TEST_PACKAGES:
  matrix:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta
install:
  - ps: Install-Product node 5
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))
test: off
deploy: off
